### ISSUE TITLE
Error after right-clicking on Spacebar Action - "Tools" (in Preferences - Keymap)

### ISSUE THREAD

**Issue by xan2622** [tin2tin/Search-API-Reference#4]
Blender verion: 2.91
Addon version: 1.5

1. Go to Edit > Preferences > Keymap 
2. Choose the default Blender keymap preset in the list 
3. Expand the "Preferences" drop-down menu
4. Next to "Spacebar Action", there are three buttons: Play, Tools, Search
5. Right-Click on "Tools" and click on "Online Python Reference"
6. This error appears: 
> Python: Traceback (most recent call last):
  File "E:\blender_stable\2.91\scripts\startup\bl_operators\wm.py", line 1120, in execute
    url = _wm_doc_get_id(self.doc_id, do_url=True, url_prefix=self._prefix)
  File "E:\blender_stable\2.91\scripts\startup\bl_operators\wm.py", line 1028, in _wm_doc_get_id
    rna_parent = rna_class.bl_rna
AttributeError: 'NoneType' object has no attribute 'bl_rna'
location: <unknown location>:-1

**Comment by tin2tin** [comment]
When I right click on the "Tools" button, I see no option to add add-ons? 

What is it you want to achieve?

**Comment by xan2622** [comment]
I was just testing the "Search API Reference" add-on on the Blender UI interface. Just to see if I could find errors.
I like testing add-ons deeply, to hunt bugs and report them to add-ons developers.

I know that "Search API Reference" is meant to be used in the Text Editor, after selecting a word. 

But since the "Search API Reference" entry appears in the right-click menu, I thought I could be interesting to test it on other different areas of the Blender Interface (just to see if it triggers an error). 

Then I got this error while right-clicking on the Spacebar Action "Tools" button.

![h4aFH86DG5](https://user-images.githubusercontent.com/1732773/103513736-78cb7900-4e6b-11eb-8dda-f9359d60d81a.gif)

**Comment by xan2622** [comment]
My bad, this error is not related to "Search API Reference". It's directly a bug in Blender 2.91 itself.
